### ISSUE TITLE
Extend with geocoder

### ISSUE THREAD

**Issue by arthurdenner** [rexxars/sanity-plugin-leaflet-input#2]
Hi! 👋🏽 

First, thank you for this input. I've been using and enjoying it a lot.

I was wondering if you'd be open to extending this plugin, adding support to a [geocoder plugin](https://github.com/Esri/esri-leaflet-geocoder).

In [this video](https://next.egghead.io/lessons/react-add-placename-location-search-to-react-leaflet-with-esri-leaflet-geocoder) you can see what the result would be like.

**Comment by arthurdenner** [comment]
@rexxars, ping.

**Comment by rexxars** [comment]
Hi!

I'd love a geocoder, but I'm not sure I have time to follow up very thoroughly right now - if you're able to make it work mostly on your own, I'd be happy to take a look at a PR!

**Comment by arthurdenner** [comment]
@rexxars, PR submitted 😉
